development:
  rest_service:
    root_url: "http://192.168.1.39:8080/Glims/rest/BtmService"
#    root_url: "http://192.168.1.190:8980/Glims/rest/BtmService"
#    root_url: "http://127.0.0.1:3000/api/v1"

test:
  rest_service:
    root_url: "http://192.168.1.39:8080/Glims/rest/BtmService"


production:
  rest_service:
    root_url: "http://192.168.1.39:8080/Glims/rest/BtmService"